version: 2
jobs:
  build:
    working_directory: ~/working_directory
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: cache-deps-{{ .Branch }}
      - run:
          name: yarn
          command: yarn
      - save_cache:
          key: cache-deps-{{ .Branch }}
          paths:
            - ./node_modules
            - ~/.cache/yarn/
      - run:
          name: test
          command: npm test
      - run:
          name: code-coverage
          command: npm run codecov

