version: 2
jobs:
  build:
    working_directory: ~/working_directory
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: yarn
          command: yarn
      - run:
          name: test
          command: npm test
      - run:
          name: code-coverage
          command: npm run cov
      - run:
          name: codecov
          command: bash <(curl -s https://codecov.io/bash) -f coverage/coverage-final.json

